all: Course

Course:  Main.cpp CombatUnit.cpp Player.cpp Enemy.cpp Encounter.cpp Room.cpp GameWorld.cpp Item.cpp Food.cpp Drink.cpp NPC.cpp StatUp.cpp Scroll.cpp Move.cpp
	g++ Main.cpp CombatUnit.cpp Player.cpp Enemy.cpp Encounter.cpp Room.cpp GameWorld.cpp Item.cpp Drink.cpp Food.cpp NPC.cpp StatUp.cpp Scroll.cpp Move.cpp -std=c++11 -o TextAdv
